// packages/jasonweb/from-vue/Minesweeper/Minesweeper.vue
<template>
  <div id="minesweeper-wrapper" class="flex flex-col justify-center" dir="ltr">
    <!-- <teleport to="head">
      <link
        v-for="(asset, index) in assets"
        :key="index"
        rel="preload"
        as="image"
        :href="`/assets/${asset}`"
      />
    </teleport> -->
    <div class="flex flex-row justify-center px-4 space-x-3">
      <!-- Options -->
      <div class="flex flex-col space-y-2">
        <div>
          <input
            id="showIndexesCheckbox"
            v-model="showIndexes"
            class="checkbox"
            type="checkbox"
          />
          <label class="inline-block" for="showIndexesCheckbox">
            Show indexes
          </label>
        </div>

        <div>
          <input
            id="autoPlayerShouldGuessCheckbox"
            v-model="autoPlaySafe"
            class="checkbox"
            type="checkbox"
          />
          <label class="inline-block" for="autoPlayerShouldGuessCheckbox">
            Only play safe moves
          </label>
        </div>
        <div v-if="!autoPlaySafe">
          <input
            id="restartOnFailureCheckbox"
            v-model="restartOnFailure"
            class="checkbox"
            type="checkbox"
          />
          <label class="inline-block" for="restartOnFailureCheckbox">
            Restart on failure
          </label>
        </div>
        <div class="mb-4">
          <label class="block text-sm font-bold mb-2" for="playerSpeed">
            Player speed
          </label>
          <input
            id="playerSpeed"
            v-model="playerSpeed"
            class="shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline"
            type="number"
            max="10"
            min="1"
          />
        </div>

        <button
          class="bg-blue-600 hover:bg-blue-800 font-semibold rounded-lg p-4 text-white"
          @click="autoPlay"
        >
          Auto play
        </button>
      </div>

      <!-- Minesweeper -->
      <div class="ms-container" @contextmenu="$event.preventDefault()">
        <span>{{ game.isGameWon ? 'You win! 🥳🥳🥳' : '' }}</span>
        <!-- Top border -->
        <div class="flex flex-row">
          <div class="ms-border-corner ms-border-top-left" />
          <div class="flex-1 ms-border-horizontal" />
          <div class="ms-border-corner ms-border-top-right" />
        </div>

        <!-- scoreboard -->
        <div class="bg-black flex flex-row justify-center items-center">
          <div class="ms-border-vertical self-stretch" />
          <div class="ms-score">
            <div :class="getDigitClass(game.minesLeft, 0)" />
            <div :class="getDigitClass(game.minesLeft, 1)" />
            <div :class="getDigitClass(game.minesLeft, 2)" />
          </div>

          <div
            class="ms-new-game-wrapper flex-1 flex justify-center"
            @click="newGame"
          >
            <button :class="smileyClass" />
          </div>

          <div class="ms-score">
            <div :class="getDigitClass(time, 0)" />
            <div :class="getDigitClass(time, 1)" />
            <div :class="getDigitClass(time, 2)" />
          </div>

          <div class="ms-border-vertical self-stretch" />
        </div>

        <!-- Middle border -->
        <div class="flex flex-row">
          <div class="ms-border-corner ms-border-middle-left" />
          <div class="flex-1 ms-border-horizontal" />
          <div class="ms-border-corner ms-border-middle-right" />
        </div>

        <div class="flex flex-row">
          <div class="ms-border-vertical" />

          <div class="ms-inner">
            <MinesweeperBoard :game="game!" />
          </div>

          <div class="ms-border-vertical" />
        </div>

        <!-- Bottom border -->
        <div class="flex flex-row">
          <div class="ms-border-corner ms-border-bottom-left" />
          <div class="flex-1 ms-border-horizontal" />
          <div class="ms-border-corner ms-border-bottom-right" />
        </div>
      </div>
    </div>
  </div>
</template>

<script lang="ts">
/* eslint-disable no-await-in-loop */
import './minesweeper.pcss';
import { computed, defineComponent, provide, Ref, ref, watch } from 'vue';
import { useRoute } from 'vue-router';
import useStopwatch from './use-stopwatch';
import MinesweeperBoard from './MinesweeperBoard.vue';
import { MinesweeperGame } from './game/minesweeper-game';
import { AutoPlayer } from './game/auto-player';
import { ShowIndexesKey } from './keys';
import { sleep } from './game/utils';

const HEIGHT = 16;
const WIDTH = 30;
const MINE_COUNT = 99;

export default defineComponent({
  name: 'Minesweeper',
  components: { MinesweeperBoard },
  setup() {
    const route = useRoute();
    const isSandbox = route.path.includes('sandbox');

    const showIndexes = ref(false);
    const autoPlaySafe = ref(false);
    const restartOnFailure = ref(true);
    const playerSpeed = ref(10);
    const autoPlayerDelay = computed(() =>
      Math.round(101 - 10 * playerSpeed.value)
    );

    provide(ShowIndexesKey, showIndexes);
    const { time, start, stop } = useStopwatch();
    const game = ref(
      new MinesweeperGame(WIDTH, HEIGHT, MINE_COUNT, isSandbox)
    ) as Ref<MinesweeperGame>;
    const player = ref(
      new AutoPlayer(game.value, !autoPlaySafe.value)
    ) as Ref<AutoPlayer>;

    game.value.onGameInit(start);
    game.value.onGameLose(stop);
    game.value.onGameWin(stop);

    const newGame = () => {
      game.value = new MinesweeperGame(WIDTH, HEIGHT, MINE_COUNT, isSandbox);
      player.value = new AutoPlayer(game.value, !autoPlaySafe.value);

      game.value.onGameInit(start);
      game.value.onGameLose(stop);
      game.value.onGameWin(stop);
    };

    watch(autoPlaySafe, () => {
      player.value.shouldGuess = !autoPlaySafe.value;
    });

    watch(autoPlayerDelay, () => {
      player.value.delay = autoPlayerDelay.value;
    });

    const autoPlay = async () => {
      if (game.value.isGameLost) {
        newGame();
      }

      player.value.autoPlay(autoPlayerDelay.value);

      while (restartOnFailure.value && !game.value.isGameWon) {
        await game.value.waitForEnd();
        if (
          !autoPlaySafe.value &&
          restartOnFailure.value &&
          game.value.isGameLost
        ) {
          await sleep(200);
          newGame();
          player.value.autoPlay(autoPlayerDelay.value);
        }
      }
    };

    newGame();

    const getDigitClass = (value: number, index: number) =>
      `ms-digit ms-digit-${value.toString().padStart(3, '0')[index]}`;

    const smileyClass = computed(() => {
      if (game.value.isGameWon) return 'ms-face ms-face-won';
      if (game.value.isGameLost) return 'ms-face ms-face-lost';

      return 'ms-face ms-face-neutral';
    });

    const assets = [
      'border_hor_2x.png',
      'border_middle_left_2x.png',
      'border_middle_right_2x.png',
      'border_vert_2x.png',
      'corner_bottom_left_2x.png',
      'corner_bottom_right_2x.png',
      'corner_up_left_2x.png',
      'corner_up_right_2x.png',
      'd0.svg',
      'd1.svg',
      'd2.svg',
      'd3.svg',
      'd4.svg',
      'd5.svg',
      'd6.svg',
      'd7.svg',
      'd8.svg',
      'd9.svg',
      'face_active.svg',
      'face_lost.svg',
      'face_neutral.svg',
      'face_pressed.svg',
      'face_won.svg',
      'flag_wrong.svg',
      'flag.svg',
      'hidden.svg',
      'logo.png',
      'mine_red.svg',
      'mine.svg',
      'nums_background.svg',
      'pressed.svg',
      'type0.svg',
      'type1.svg',
      'type2.svg',
      'type3.svg',
      'type4.svg',
      'type5.svg',
      'type6.svg',
      'type7.svg',
      'type8.svg',
    ];

    return {
      assets,
      game,
      time,
      newGame,
      autoPlay,
      showIndexes,
      autoPlaySafe,
      playerSpeed,
      restartOnFailure,
      getDigitClass,
      smileyClass,
    };
  },
});
</script>

<style scoped>
.checkbox {
  @apply w-4 h-4 bg-gray-50 rounded border border-gray-300 focus:ring-blue-300 dark:bg-gray-700 dark:border-gray-600 dark:focus:ring-blue-600 dark:ring-offset-gray-800 cursor-pointer mr-1;
}

#minesweeper-wrapper::after {
  position: absolute;
  width: 0;
  height: 0;
  overflow: hidden;
  z-index: -1;
  content: url('/assets/border_hor_2x.png')
    url('/assets/border_middle_left_2x.png')
    url('/assets/border_middle_right_2x.png') url('/assets/border_vert_2x.png')
    url('/assets/corner_bottom_left_2x.png')
    url('/assets/corner_bottom_right_2x.png')
    url('/assets/corner_up_left_2x.png') url('/assets/corner_up_right_2x.png')
    url('/assets/d0.svg') url('/assets/d1.svg') url('/assets/d2.svg')
    url('/assets/d3.svg') url('/assets/d4.svg') url('/assets/d5.svg')
    url('/assets/d6.svg') url('/assets/d7.svg') url('/assets/d8.svg')
    url('/assets/d9.svg') url('/assets/face_active.svg')
    url('/assets/face_lost.svg') url('/assets/face_neutral.svg')
    url('/assets/face_pressed.svg') url('/assets/face_won.svg')
    url('/assets/flag_wrong.svg') url('/assets/flag.svg')
    url('/assets/hidden.svg') url('/assets/logo.png')
    url('/assets/mine_red.svg') url('/assets/mine.svg')
    url('/assets/nums_background.svg') url('/assets/pressed.svg')
    url('/assets/type0.svg') url('/assets/type1.svg') url('/assets/type2.svg')
    url('/assets/type3.svg') url('/assets/type4.svg') url('/assets/type5.svg')
    url('/assets/type6.svg') url('/assets/type7.svg') url('/assets/type8.svg');
}
</style>

// packages/jasonweb/src/features/Minesweeper/index.tsx
import './styles.scss';

import { useMemo, useRef, useState } from 'react';
import { useLocation } from 'react-router-dom'; // Assuming react-router-dom is used for routing

import { AutoPlayer } from './game/auto-player';
import { MinesweeperGame } from './game/minesweeper-game';
import { sleep } from './game/utils';
import MinesweeperBoard from './MinesweeperBoard';

const HEIGHT = 16;
const WIDTH = 30;
const MINE_COUNT = 99;

export function Component() {
  const location = useLocation();
  const isSandbox = location.pathname.includes('sandbox');

  const [showIndexes, setShowIndexes] = useState(false);
  const [autoPlaySafe, setAutoPlaySafe] = useState(false);
  const [restartOnFailure, setRestartOnFailure] = useState(true);
  const [playerSpeed, setPlayerSpeed] = useState(10);

  const autoPlayerDelay = useMemo(() => Math.round(101 - 10 * playerSpeed), [playerSpeed]);

  const [game, setGame] = useState(() => new MinesweeperGame(WIDTH, HEIGHT, MINE_COUNT, isSandbox));
  const [player, setPlayer] = useState(() => new AutoPlayer(game, !autoPlaySafe));

  const [time, setTime] = useState(0);
  const timeInterval = useRef<number | null>(null);

  const newGame = () => {
    setGame(new MinesweeperGame(WIDTH, HEIGHT, MINE_COUNT, isSandbox));
    setPlayer(new AutoPlayer(game, !autoPlaySafe));
    setTime(0);

    const startTimer = () => {
      timeInterval.current = setInterval(() => {
        setTime((p) => p + 1);
      }, 1000);
    };

    const stopTimer = () => {
      if (timeInterval.current) {
        clearInterval(timeInterval.current);
      }
    };

    game.onGameInit(startTimer);
    game.onGameLose(stopTimer);
    game.onGameWin(stopTimer);
  };

  const autoPlay = async () => {
    if (game.isGameLost) {
      newGame();
    }

    player.autoPlay(autoPlayerDelay);

    while (restartOnFailure && !game.isGameWon) {
      // eslint-disable-next-line no-await-in-loop
      await game.waitForEnd();
      if (!autoPlaySafe && restartOnFailure && game.isGameLost) {
        // eslint-disable-next-line no-await-in-loop
        await sleep(200);
        newGame();
        player.autoPlay(autoPlayerDelay);
      }
    }
  };

  const getDigitClass = (value: number, index: number) =>
    `ms-digit ms-digit-${value.toString().padStart(3, '0')[index]}`;

  const smileyClass = useMemo(() => {
    if (game.isGameWon) return 'ms-face ms-face-won';
    if (game.isGameLost) return 'ms-face ms-face-lost';
    return 'ms-face ms-face-neutral';
  }, [game.isGameWon, game.isGameLost]);

  const assets = [
    'border_hor_2x.png',
    'border_middle_left_2x.png',
    'border_middle_right_2x.png',
    'border_vert_2x.png',
    'corner_bottom_left_2x.png',
    'corner_bottom_right_2x.png',
    'corner_up_left_2x.png',
    'corner_up_right_2x.png',
    'd0.svg',
    'd1.svg',
    'd2.svg',
    'd3.svg',
    'd4.svg',
    'd5.svg',
    'd6.svg',
    'd7.svg',
    'd8.svg',
    'd9.svg',
    'face_active.svg',
    'face_lost.svg',
    'face_neutral.svg',
    'face_pressed.svg',
    'face_won.svg',
    'flag_wrong.svg',
    'flag.svg',
    'hidden.svg',
    'logo.png',
    'mine_red.svg',
    'mine.svg',
    'nums_background.svg',
    'pressed.svg',
    'type0.svg',
    'type1.svg',
    'type2.svg',
    'type3.svg',
    'type4.svg',
    'type5.svg',
    'type6.svg',
    'type7.svg',
    'type8.svg',
  ];

  return (
    <div id="minesweeper-wrapper" className="flex flex-col justify-center mt-16" dir="ltr">
      <div className="flex flex-row justify-center px-4 space-x-3">
        <div className="flex flex-col space-y-2">
          <div>
            <label className="inline-block" htmlFor="showIndexesCheckbox">
              <input
                id="showIndexesCheckbox"
                className="checkbox"
                type="checkbox"
                checked={showIndexes}
                onChange={(e) => setShowIndexes(e.target.checked)}
              />
              Show indexes
            </label>
          </div>
          <div>
            <label className="inline-block" htmlFor="autoPlayerShouldGuessCheckbox">
              <input
                id="autoPlayerShouldGuessCheckbox"
                className="checkbox"
                type="checkbox"
                checked={autoPlaySafe}
                onChange={(e) => setAutoPlaySafe(e.target.checked)}
              />
              Only play safe moves
            </label>
          </div>
          {!autoPlaySafe && (
            <div>
              <label className="inline-block" htmlFor="restartOnFailureCheckbox">
                <input
                  id="restartOnFailureCheckbox"
                  className="checkbox"
                  type="checkbox"
                  checked={restartOnFailure}
                  onChange={(e) => setRestartOnFailure(e.target.checked)}
                />
                Restart on failure
              </label>
            </div>
          )}
          <div className="mb-4">
            <label className="block text-sm font-bold mb-2" htmlFor="playerSpeed">
              <input
                id="playerSpeed"
                className="shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline"
                type="number"
                max="10"
                min="1"
                value={playerSpeed}
                onChange={(e) => setPlayerSpeed(Number(e.target))}
              />
              Player speed
            </label>
          </div>
          <button
            type="button"
            className="bg-blue-600 hover:bg-blue-800 font-semibold rounded-lg p-4 text-white"
            onClick={autoPlay}
          >
            Auto play
          </button>
        </div>
        <div className="ms-container">
          {game.isGameWon && <span>You win! 🥳🥳🥳</span>}
          <div className="flex flex-row">
            <div className="ms-border-corner ms-border-top-left" />
            <div className="flex-1 ms-border-horizontal" />
            <div className="ms-border-corner ms-border-top-right" />
          </div>
          <div className="bg-black flex flex-row justify-center items-center">
            <div className="ms-border-vertical self-stretch" />
            <div className="ms-score">
              <div className={getDigitClass(game.minesLeft, 0)} />
              <div className={getDigitClass(game.minesLeft, 1)} />
              <div className={getDigitClass(game.minesLeft, 2)} />
            </div>
            {/* eslint-disable-next-line jsx-a11y/click-events-have-key-events, jsx-a11y/no-static-element-interactions */}
            <div className="ms-new-game-wrapper flex-1 flex justify-center" onClick={newGame}>
              <button type="button" aria-label="New Game" className={smileyClass} />
            </div>
            <div className="ms-score">
              <div className={getDigitClass(time, 0)} />
              <div className={getDigitClass(time, 1)} />
              <div className={getDigitClass(time, 2)} />
            </div>
            <div className="ms-border-vertical self-stretch" />
          </div>
          <div className="flex flex-row">
            <div className="ms-border-vertical" />
            <div className="ms-inner">
              <MinesweeperBoard game={game} showIndexes={showIndexes} />
            </div>
            <div className="ms-border-vertical" />
          </div>
          <div className="flex flex-row">
            <div className="ms-border-corner ms-border-bottom-left" />
            <div className="flex-1 ms-border-horizontal" />
            <div className="ms-border-corner ms-border-bottom-right" />
          </div>
        </div>
      </div>
    </div>
  );
}

Component.displayName = 'Minesweeper';

export default Component;
